"use client";
import {useEffect,useMemo,useRef,useState} from"react";
import{Bell,BookMarked,BookOpen,Camera,Check,ChevronLeft,Clock3,Home,LibraryBig,ListFilter,LoaderCircle,Menu,Plus,RotateCcw,Search,ShoppingBag,Sparkles,Star,Trash2,Users,X}from"lucide-react";

type Copy={id:string;owner:string;location:string;status:"available"|"loaned";borrower?:string;loanedAt?:string};
type Rating={member:string;stars:number;text:string};
type Book={id:string;title:string;author:string;genre:string;cover?:string;color:string;isbn?:string;copies:Copy[];readers:string[];ratings:Rating[];createdAt:string};
type AppState={members:{name:string;color:string}[];books:Book[];wishlist:{id:string;title:string;requestedBy:string}[];history:{id:string;book:string;borrower:string;date:string}[]};
type Hit={title:string;author:string;isbn?:string;cover?:string;year?:string;source:string;confidence?:number};
const uid=()=>crypto.randomUUID();
const norm=(s:string)=>s.toLowerCase().normalize("NFKD").replace(/[\u0591-\u05C7]/g,"").replace(/[^\p{L}\p{N}]/gu,"");
const distance=(a:string,b:string)=>{const x=norm(a),y=norm(b),row=Array.from({length:y.length+1},(_,i)=>i);for(let i=1;i<=x.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=y.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,prev+(x[i-1]===y[j-1]?0:1));prev=old}}return row[y.length]};
const fuzzy=(value:string,q:string)=>{const v=norm(value),n=norm(q);if(!n)return true;if(v.includes(n))return true;return value.split(/\s+/).some(word=>distance(word,q)<=Math.max(1,Math.floor(n.length/4)))};
const members=[{name:"אורי",color:"#b57945"},{name:"נועם",color:"#496f87"},{name:"דניאלה",color:"#8e5b74"},{name:"רוני",color:"#66794f"},{name:"אבא",color:"#735a47"},{name:"אמא",color:"#9a5c68"}];
const mk=(title:string,author:string,owner:string,color:string,genre="ספרות ישראלית"):Book=>({id:uid(),title,author,genre,color,copies:[{id:uid(),owner,location:"הבית המשותף",status:"available"}],readers:[],ratings:[],createdAt:new Date().toISOString()});
const defaults:AppState={members,books:[mk("כימים אחדים","מאיר שלו","אורי","#846044"),mk("הנסיך הקטן","אנטואן דה סנט־אכזופרי","דניאלה","#2f6577","קלאסיקה"),mk("קיצור תולדות האנושות","יובל נח הררי","נועם","#9a6846","עיון"),mk("1984","ג'ורג' אורוול","רוני","#793f3a","קלאסיקה")],wishlist:[],history:[]};

function Cover({b,small=false}:{b:Book;small?:boolean}){return b.cover?<img className={`real-cover ${small?"small":""}`} src={b.cover} alt={`כריכת ${b.title}`}/>:<div className={`cover ${small?"small":""}`} style={{background:b.color}}><span>✦</span><b>{b.title}</b><small>{b.author}</small></div>}
function Modal({children,close,wide=false}:{children:React.ReactNode;close:()=>void;wide?:boolean}){return <div className="backdrop" onMouseDown={close}><div className={`sheet ${wide?"wide":""}`} onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button>{children}</div></div>}

export default function Page(){
 const[state,setState]=useState<AppState>(defaults),[loaded,setLoaded]=useState(false),[saving,setSaving]=useState(false),[view,setView]=useState("home"),[query,setQuery]=useState(""),[searchPick,setSearchPick]=useState(""),[memberFilter,setMemberFilter]=useState("הכול"),[genre,setGenre]=useState("הכול"),[modal,setModal]=useState(""),[selected,setSelected]=useState<Book|null>(null),[loanTarget,setLoanTarget]=useState(""),[toast,setToast]=useState(""),[photos,setPhotos]=useState<string[]>([]),[ocr,setOcr]=useState(0),[hits,setHits]=useState<Hit[]>([]),[searchQ,setSearchQ]=useState(""),[busy,setBusy]=useState(false);
 const fileRef=useRef<HTMLInputElement>(null),saveTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2500)};
 useEffect(()=>{fetch("/api/state").then(r=>r.json()).then(d=>{if(d.state)setState(d.state);else fetch("/api/state",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(defaults)});setLoaded(true)}).catch(()=>{setLoaded(true);notify("אין כרגע חיבור לענן — השינויים יישמרו כשיחזור")})},[]);
 const update=(fn:(s:AppState)=>AppState)=>{setState(prev=>{const next=fn(prev);if(loaded){if(saveTimer.current)clearTimeout(saveTimer.current);saveTimer.current=setTimeout(async()=>{setSaving(true);try{const r=await fetch("/api/state",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(next)});if(!r.ok)throw Error();}catch{notify("השמירה נכשלה — נסו שוב") }finally{setSaving(false)}},500)}return next})};
 const filtered=useMemo(()=>state.books.filter(b=>(!searchPick||b.id===searchPick)&&(!query||fuzzy(b.title,query)||fuzzy(b.author,query))&&(genre==="הכול"||b.genre===genre)&&(memberFilter==="הכול"||b.copies.some(c=>c.owner===memberFilter))),[state.books,query,genre,memberFilter,searchPick]);
 const suggestions=useMemo(()=>query.trim()?state.books.filter(b=>fuzzy(b.title,query)||fuzzy(b.author,query)).slice(0,5):[],[state.books,query]);
 const loaned=state.books.flatMap(b=>b.copies.filter(c=>c.status==="loaned").map(c=>({b,c})));
 const reading=state.books.filter(b=>b.readers.length);
 const average=(b:Book)=>b.ratings.length?(b.ratings.reduce((n,r)=>n+r.stars,0)/b.ratings.length).toFixed(1):"—";
 const recentlyAdded=[...state.books].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,4);
 const topRated=[...state.books].filter(b=>b.ratings.length).sort((a,b)=>Number(average(b))-Number(average(a))).slice(0,4);
 const loanedBooks=state.books.filter(b=>b.copies.some(c=>c.status==="loaned")).slice(0,4);
 const genres=["הכול",...Array.from(new Set(state.books.map(b=>b.genre)))];
 const openBook=(b:Book)=>{setSelected(b);setModal("detail")};
 const addHit=(hit:Hit)=>{setSelected({...mk(hit.title,hit.author,state.members[0].name,"#395f52","לא מסווג"),cover:hit.cover,isbn:hit.isbn});setModal("form")};
 const quickLoan=(b:Book)=>{setLoanTarget(b.id);setModal("loan")};
 const searchBooks=async(q=searchQ)=>{if(!q.trim())return;setBusy(true);try{const d=await fetch(`/api/search-books?q=${encodeURIComponent(q)}`).then(r=>r.json());setHits(d.results||[])}catch{notify("החיפוש נכשל") }finally{setBusy(false)}};
 const takePhoto=(file?:File)=>{if(!file)return;const rd=new FileReader();rd.onload=()=>typeof rd.result==="string"&&setPhotos(p=>[...p,rd.result as string]);rd.readAsDataURL(file)};
 const recognizeWithOcr=async()=>{const{createWorker}=await import("tesseract.js");const worker=await createWorker(["heb","eng"],1,{logger:m=>m.status.includes("recognizing")&&setOcr(Math.max(5,Math.round((m.progress||0)*100)))});let text="";for(const p of photos){const r=await worker.recognize(p);text+=`\n${r.data.text}`}await worker.terminate();const lines=[...new Set(text.split("\n").map(x=>x.replace(/[^\p{L}\p{N}\s'״׳-]/gu," ").replace(/\s+/g," ").trim()).filter(x=>x.length>3))].slice(0,6);const result:Hit[]=[];for(const line of lines.slice(0,4)){const d=await fetch(`/api/search-books?q=${encodeURIComponent(line)}`).then(r=>r.json());result.push(...(d.results||[]).slice(0,3))}return{hits:[...new Map(result.map(x=>[(x.isbn||x.title+x.author),x])).values()],query:lines.join(" ")}};
 const recognize=async()=>{if(!photos.length)return;setBusy(true);setOcr(15);try{const response=await fetch("/api/recognize",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({images:photos})});if(!response.ok)throw Error("gemini");const data=await response.json() as {books:Array<{title:string;author?:string;isbn?:string;confidence:number}>};setOcr(65);const result:Hit[]=[];for(const book of data.books||[]){const q=[book.isbn,book.title,book.author].filter(Boolean).join(" ");let verified:Hit|undefined;try{const d=await fetch(`/api/search-books?q=${encodeURIComponent(q)}`).then(r=>r.json());verified=d.results?.[0]}catch{}result.push(verified?{...verified,confidence:book.confidence}:{title:book.title,author:book.author||"",isbn:book.isbn,source:"Gemini",confidence:book.confidence})}setOcr(100);setHits([...new Map(result.map(x=>[(x.isbn||x.title+x.author),x])).values()]);setSearchQ((data.books||[]).map(x=>x.title).join(" "));setModal("results");if(!result.length)notify("לא זוהו ספרים בוודאות — נסו צילום קרוב ומואר יותר");}catch{notify("Gemini לא היה זמין — עברנו לזיהוי OCR הרגיל");try{const fallback=await recognizeWithOcr();setHits(fallback.hits);setSearchQ(fallback.query);setModal("results")}catch{notify("לא הצלחנו לקרוא את התמונה. אפשר לחפש ידנית.");setModal("search")}}finally{setBusy(false);setOcr(0)}};
 const nav=[["home",Home,"בית"],["library",LibraryBig,"הספרייה"],["add",Plus,"הוספה"],["loans",BookMarked,"השאלות"],["more",Menu,"עוד"]]as const;
 if(!loaded)return <div className="loading"><BookOpen/><LoaderCircle className="spin"/><b>פותחים את הספרייה…</b></div>;
 return <div className="app" dir="rtl"><header><div className="brand"><i><BookOpen/></i><div><b>הספרייה של משפחת אברהם</b><span>{saving?"שומר…":"נשמר בענן"}</span></div></div><LibrarySearch query={query} suggestions={suggestions} setQuery={q=>{setQuery(q);setSearchPick("")}} pick={b=>{setQuery(b.title);setSearchPick(b.id);setView("library")}} clear={()=>{setQuery("");setSearchPick("")}}/><div className="head-actions"><button className="bell"><Bell/><i/></button><button><Users/><span>{state.members.length}</span></button></div></header>
 <aside><nav>{nav.map(([id,I,label])=><button key={id} className={view===id?"active":""} onClick={()=>id==="add"?setModal("add"):setView(id)}><I/>{label}</button>)}</nav><div className="family"><span>בני המשפחה</span>{state.members.map(p=><button key={p.name}><i style={{background:p.color}}>{p.name[0]}</i>{p.name}</button>)}</div></aside>
 <main><div className="mobile"><LibrarySearch query={query} suggestions={suggestions} setQuery={q=>{setQuery(q);setSearchPick("")}} pick={b=>{setQuery(b.title);setSearchPick(b.id);setView("library")}} clear={()=>{setQuery("");setSearchPick("")}}/></div>
 {view==="home"&&<><section className="welcome"><div><span className="eyebrow">הספרייה המשפחתית שלכם</span><h1>מה תרצו לקרוא היום?</h1><p>{state.books.length} כותרים · {state.books.reduce((n,b)=>n+b.copies.length,0)} עותקים</p></div><div className="quick"><button className="primary" onClick={()=>setModal("camera")}><Camera/><span><b>צילום ספרים</b><small>זיהוי כריכות ושדרות</small></span></button><button onClick={()=>setModal("loan")}><RotateCcw/><span><b>רישום השאלה</b><small>בפחות מחצי דקה</small></span></button></div></section>
 {reading.length>0&&<section><Title icon={<BookOpen/>} text="קוראים עכשיו"/><div className="reading">{reading.map(b=><article key={b.id}><Cover b={b} small/><div><span className="reader">{b.readers.join(" ו")} קוראים</span><h3>{b.title}</h3><p>{b.author}</p><button onClick={()=>update(s=>({...s,books:s.books.map(x=>x.id===b.id?{...x,readers:[]}:x)}))}><Check/>סיימנו</button></div></article>)}</div></section>}
 {loaned.some(({c})=>Date.now()-new Date(c.loanedAt||0).getTime()>15_552_000_000)&&<section className="reminder"><i><Clock3/></i><div><span>דורש תשומת לב</span><h3>יש ספר שמושאל יותר מחצי שנה</h3><p>אולי הגיע הזמן לבדוק מה שלומו.</p></div><button onClick={()=>setView("loans")}>לפרטים<ChevronLeft/></button></section>}
 {recentlyAdded.length>0&&<section><Title icon={<Sparkles/>} text="נוספו לאחרונה"/><Grid books={recentlyAdded} open={openBook} average={average} loan={quickLoan}/></section>}
 {topRated.length>0&&<section><Title icon={<Star/>} text="בדירוג הגבוה ביותר"/><Grid books={topRated} open={openBook} average={average} loan={quickLoan}/></section>}
 {loanedBooks.length>0&&<section><Title icon={<BookMarked/>} text="מושאלים כרגע"/><Grid books={loanedBooks} open={openBook} average={average}/></section>}</>}
 {view==="library"&&<section className="page"><Head title="הספרייה" sub={`${filtered.length} מתוך ${state.books.length} כותרים`} action={()=>setModal("add")}/><div className="filter-label">לפי בן משפחה</div><div className="filters member-filters"><Users/><button className={memberFilter==="הכול"?"active":""} onClick={()=>setMemberFilter("הכול")}>כולם</button>{state.members.map(m=><button key={m.name} className={memberFilter===m.name?"active":""} onClick={()=>setMemberFilter(m.name)}>{m.name}</button>)}</div><div className="filter-label">לפי סוגה</div><div className="filters"><ListFilter/>{genres.map(g=><button key={g} className={genre===g?"active":""} onClick={()=>setGenre(g)}>{g}</button>)}</div>{filtered.length?<Grid books={filtered} open={openBook} average={average} loan={quickLoan}/>:<Empty/>}</section>}
 {view==="loans"&&<section className="page"><Head title="השאלות" sub={`${loaned.length} ספרים נמצאים מחוץ לבית`} action={()=>setModal("loan")}/>{loaned.length?loaned.map(({b,c})=><article className="loan" key={c.id}><Cover b={b} small/><div><span>מושאל</span><h2>{b.title}</h2><p>{b.author}</p><dl><div><dt>אצל מי?</dt><dd>{c.borrower}</dd></div><div><dt>מתאריך</dt><dd>{c.loanedAt&&new Date(c.loanedAt).toLocaleDateString("he-IL")}</dd></div><div><dt>בעלים</dt><dd>{c.owner}</dd></div></dl></div><button className="returned" onClick={()=>update(s=>({...s,books:s.books.map(x=>x.id===b.id?{...x,copies:x.copies.map(y=>y.id===c.id?{...y,status:"available",location:"הבית המשותף",borrower:undefined,loanedAt:undefined}:y)}:x),history:[{id:uid(),book:b.title,borrower:c.borrower||"",date:new Date().toISOString()},...s.history]}))}><Check/>הספר הוחזר</button></article>):<div className="empty"><Check/><h3>כל הספרים בבית</h3><p>אין כרגע ספרים מושאלים.</p></div>}</section>}
 {view==="more"&&<section className="page"><Head title="עוד" sub="קריאה, דירוגים ורשימת קניות"/><div className="more-grid"><button className="more-card" onClick={()=>setModal("reading")}><i><Users/></i><div><h3>קוראים עכשיו</h3><p>{reading.length} ספרים בקריאה</p></div><ChevronLeft/></button><button className="more-card" onClick={()=>setModal("wishlist")}><i><ShoppingBag/></i><div><h3>רוצים לקנות</h3><p>{state.wishlist.length} ספרים ברשימה</p></div><ChevronLeft/></button><button className="more-card" onClick={()=>setView("library")}><i><Star/></i><div><h3>דירוגים וביקורות</h3><p>בתוך כל ספר</p></div><ChevronLeft/></button></div></section>}
 </main><nav className="bottom">{nav.map(([id,I,label])=><button key={id} className={view===id?"active":""} onClick={()=>id==="add"?setModal("add"):setView(id)}><I/><span>{label}</span></button>)}</nav>
 {modal==="add"&&<Modal close={()=>setModal("")}><Mark/><h2>הוספת ספר</h2><p>איך תרצו להוסיף אותו?</p><div className="options"><Opt icon={<Camera/>} title="צילום ספרים" text="OCR וחיפוש אוטומטי" click={()=>setModal("camera")}/><Opt icon={<Search/>} title="חיפוש לפי שם או ISBN" text="Google Books ו־Open Library" click={()=>setModal("search")}/><Opt icon={<Plus/>} title="הזנה ידנית" text="שם, מחבר ובעלים" click={()=>{setSelected(mk("","",state.members[0].name,"#456b5d"));setModal("form")}}/></div></Modal>}
 {modal==="search"&&<Modal close={()=>setModal("")} wide><h2>חיפוש במאגרי ספרים</h2><div className="modal-search"><input autoFocus value={searchQ} onChange={e=>setSearchQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&searchBooks() } placeholder="שם ספר, מחבר או ISBN"/><button className="solid" onClick={()=>searchBooks()}>{busy?<LoaderCircle className="spin"/>:<Search/>}חיפוש</button></div><Results hits={hits} add={addHit}/></Modal>}
 {modal==="camera"&&<Modal close={()=>setModal("")} wide><div className="camera-heading"><i><Camera/></i><div><h2>צילום ספרים</h2><p>צלמו כריכות או שדרות ישרות ובאור טוב.</p></div></div><input ref={fileRef} className="camera-input" type="file" accept="image/*" capture="environment" onChange={e=>{takePhoto(e.target.files?.[0]);e.currentTarget.value=""}}/>{photos.length?<><div className="photo-grid">{photos.map((p,i)=><div key={i}><img src={p} alt="צילום ספרים"/><button onClick={()=>setPhotos(x=>x.filter((_,j)=>j!==i))}><X/></button></div>)}</div><div className="camera-actions"><button className="secondary" onClick={()=>fileRef.current?.click()}><Camera/>צילום נוסף</button><button className="solid" disabled={busy} onClick={recognize}>{busy?<LoaderCircle className="spin"/>:<Sparkles/>}{busy?`מזהה… ${ocr}%`:"זיהוי הספרים"}</button></div></>:<button className="camera-empty" onClick={()=>fileRef.current?.click()}><Camera/><b>פתיחת המצלמה</b><span>אפשר גם לבחור תמונה מהגלריה</span></button>}</Modal>}
 {modal==="results"&&<Modal close={()=>setModal("")} wide><h2>ספרים שזוהו</h2><p>סמנו כמה ספרים, בחרו בעלים ואשרו יחד.</p>{hits.length?<BatchResults hits={hits} members={state.members.map(x=>x.name)} save={(chosen,owner)=>{update(s=>({...s,books:[...chosen.map(h=>({...mk(h.title,h.author||"מחבר לא ידוע",owner,"#395f52","לא מסווג"),cover:h.cover,isbn:h.isbn})),...s.books]}));setModal("");setPhotos([]);notify(`${chosen.length} ספרים נוספו לספרייה`)}}/>:<Empty/>}</Modal>}
 {modal==="form"&&selected&&<BookForm book={selected} members={state.members.map(x=>x.name)} close={()=>setModal("")} save={b=>{update(s=>({...s,books:[b,...s.books]}));setModal("");setPhotos([]);notify("הספר נוסף לספרייה")}}/>}
 {modal==="loan"&&<LoanForm books={state.books} initialBookId={loanTarget} close={()=>{setModal("");setLoanTarget("")}} save={(bookId,copyId,name)=>{update(s=>({...s,books:s.books.map(b=>b.id===bookId?{...b,copies:b.copies.map(c=>c.id===copyId?{...c,status:"loaned",borrower:name,loanedAt:new Date().toISOString(),location:`אצל ${name}`}:c)}:b)}));setModal("");setLoanTarget("");notify("ההשאלה נרשמה בהצלחה")}}/>}
 {modal==="detail"&&selected&&<BookDetail book={state.books.find(b=>b.id===selected.id)||selected} members={state.members.map(x=>x.name)} close={()=>setModal("")} change={b=>{update(s=>({...s,books:s.books.map(x=>x.id===b.id?b:x)}));setSelected(b)}} remove={()=>{update(s=>({...s,books:s.books.filter(x=>x.id!==selected.id)}));setModal("");notify("הספר נמחק")}}/>}
 {modal==="wishlist"&&<Wishlist state={state} close={()=>setModal("")} update={update}/>} {modal==="reading"&&<Reading state={state} close={()=>setModal("")} update={update}/>} {toast&&<div className="toast"><Check/>{toast}</div>}</div>
}

function Title({icon,text}:{icon:React.ReactNode;text:string}){return <div className="section-title"><div>{icon}<h2>{text}</h2></div></div>};
function Head({title,sub,action}:{title:string;sub:string;action?:()=>void}){return <div className="page-head"><div><span className="eyebrow">הספרייה של משפחת אברהם</span><h1>{title}</h1><p>{sub}</p></div>{action&&<button className="solid" onClick={action}><Plus/>הוספה</button>}</div>};
function Grid({books,open,average,loan}:{books:Book[];open:(b:Book)=>void;average:(b:Book)=>string;loan?:(b:Book)=>void}){return <div className="book-grid">{books.map(b=>{const available=b.copies.some(c=>c.status==="available");return <article className="book-card" key={b.id}><button className="book-open" onClick={()=>open(b)}><div className="cover-wrap"><Cover b={b}/><span className={available?"status available":"status loaned"}>{available?"זמין":"מושאל"}</span></div><div><h3>{b.title}</h3><p>{b.author}</p><footer>{b.copies.map(c=>c.owner).join(", ")}<em><Star size={13} fill="currentColor"/>{average(b)}</em></footer></div></button>{loan&&available&&<button className="quick-loan" onClick={()=>loan(b)}><RotateCcw/>השאלה</button>}</article>})}</div>};
function Empty(){return <div className="empty"><BookOpen/><h3>עדיין אין כאן ספרים</h3><p>הוסיפו ספר בצילום, בחיפוש או ידנית.</p></div>};
function Mark(){return <i className="sheet-mark"><BookOpen/></i>};
function Opt({icon,title,text,click}:{icon:React.ReactNode;title:string;text:string;click:()=>void}){return <button onClick={click}>{icon}<span><b>{title}</b><small>{text}</small></span><ChevronLeft/></button>};
function Results({hits,add}:{hits:Hit[];add:(h:Hit)=>void}){return <div className="results">{hits.map((h,i)=><button key={`${h.isbn}${i}`} onClick={()=>add(h)}>{h.cover?<img src={h.cover} alt=""/>:<i><BookOpen/></i>}<span><b>{h.title}</b><small>{h.author||"מחבר לא ידוע"}</small><em>{h.source}{h.year?` · ${h.year}`:""}{h.confidence!=null?` · ודאות ${h.confidence}%`:""}</em></span><Plus/></button>)}</div>};
function LibrarySearch({query,suggestions,setQuery,pick,clear}:{query:string;suggestions:Book[];setQuery:(q:string)=>void;pick:(b:Book)=>void;clear:()=>void}){const[focus,setFocus]=useState(false);return <div className="smart-search"><div className="search"><Search/><input value={query} onFocus={()=>setFocus(true)} onBlur={()=>setTimeout(()=>setFocus(false),150)} onChange={e=>setQuery(e.target.value)} placeholder="חיפוש לפי שם ספר או מחבר"/>{query&&<button onClick={clear}><X/></button>}</div>{focus&&query&&<div className="suggestions">{suggestions.length?suggestions.map(b=><button key={b.id} onMouseDown={()=>pick(b)}><Cover b={b} small/><span><b>{b.title}</b><small>{b.author}</small><em>{b.copies.some(c=>c.status==="available")?"זמין להשאלה":"מושאל כרגע"}</em></span></button>):<p>לא נמצא ספר מתאים</p>}</div>}</div>};
function BatchResults({hits,members,save}:{hits:Hit[];members:string[];save:(hits:Hit[],owner:string)=>void}){const[selected,setSelected]=useState(()=>hits.map((_,i)=>i)),[owner,setOwner]=useState(members[0]);return <div><div className="batch-list">{hits.map((h,i)=><label key={`${h.isbn}${i}`} className={selected.includes(i)?"chosen":""}><input type="checkbox" checked={selected.includes(i)} onChange={()=>setSelected(s=>s.includes(i)?s.filter(x=>x!==i):[...s,i])}/>{h.cover?<img src={h.cover} alt=""/>:<i><BookOpen/></i>}<span><b>{h.title}</b><small>{h.author||"מחבר לא ידוע"}</small><em>{h.confidence!=null?`ודאות ${h.confidence}%`:h.source}</em></span></label>)}</div><div className="batch-actions"><label>הבעלים של הספרים<select value={owner} onChange={e=>setOwner(e.target.value)}>{members.map(m=><option key={m}>{m}</option>)}</select></label><button className="solid" disabled={!selected.length} onClick={()=>save(selected.map(i=>hits[i]),owner)}><Check/>הוספת {selected.length} ספרים</button></div></div>};
function BookForm({book,members,close,save}:{book:Book;members:string[];close:()=>void;save:(b:Book)=>void}){const[b,setB]=useState(book),[owner,setOwner]=useState(members[0]),[location,setLocation]=useState("הבית המשותף");return <Modal close={close}><h2>בדיקת פרטי הספר</h2><div className="form"><label>שם הספר<input value={b.title} onChange={e=>setB({...b,title:e.target.value})}/></label><label>מחבר<input value={b.author} onChange={e=>setB({...b,author:e.target.value})}/></label><label>סוגה<input value={b.genre} onChange={e=>setB({...b,genre:e.target.value})}/></label><label>בעלים<select value={owner} onChange={e=>setOwner(e.target.value)}>{members.map(x=><option key={x}>{x}</option>)}</select></label><label>מיקום<select value={location} onChange={e=>setLocation(e.target.value)}><option>הבית המשותף</option>{members.map(x=><option key={x}>הבית של {x}</option>)}</select></label><button className="solid full" disabled={!b.title||!b.author} onClick={()=>save({...b,copies:[{id:uid(),owner,location,status:"available"}]})}><Check/>הוספה לספרייה</button></div></Modal>}
function LoanForm({books,initialBookId,close,save}:{books:Book[];initialBookId?:string;close:()=>void;save:(b:string,c:string,n:string)=>void}){const available=books.flatMap(b=>b.copies.filter(c=>c.status==="available").map(c=>({b,c})));const initial=available.find(x=>x.b.id===initialBookId);const[step,setStep]=useState(initial?2:1),[chosen,setChosen]=useState(initial?`${initial.b.id}|${initial.c.id}`:""),[name,setName]=useState(""),[q,setQ]=useState("");const matches=available.filter(({b})=>!q||fuzzy(b.title,q)||fuzzy(b.author,q));const item=available.find(x=>`${x.b.id}|${x.c.id}`===chosen);return <Modal close={close} wide><div className="loan-progress"><span className={step>=1?"active":""}>1. ספר</span><i/><span className={step>=2?"active":""}>2. שואל</span><i/><span className={step>=3?"active":""}>3. אישור</span></div>{step===1&&<><h2>איזה ספר משאילים?</h2><div className="loan-search"><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="חיפוש בשם הספר או המחבר"/></div><div className="loan-options">{matches.map(({b,c})=><button key={c.id} onClick={()=>{setChosen(`${b.id}|${c.id}`);setStep(2)}}><Cover b={b} small/><span><b>{b.title}</b><small>{b.author}</small><em>בעלים: {c.owner} · {c.location}</em></span><ChevronLeft/></button>)}{!matches.length&&<p>לא נמצאו ספרים זמינים שמתאימים לחיפוש.</p>}</div></>}{step===2&&<><h2>למי הספר מושאל?</h2>{item&&<div className="loan-summary"><Cover b={item.b} small/><span><b>{item.b.title}</b><small>{item.b.author}</small></span></div>}<div className="form"><label>שם השואל<input autoFocus value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&name.trim()&&setStep(3)} placeholder="לדוגמה: יוסי"/></label><div className="step-actions"><button className="secondary" onClick={()=>setStep(1)}>חזרה</button><button className="solid" disabled={!name.trim()} onClick={()=>setStep(3)}>המשך<ChevronLeft/></button></div></div></>}{step===3&&item&&<><h2>מוודאים ושומרים</h2><div className="confirm-loan"><Cover b={item.b} small/><dl><div><dt>ספר</dt><dd>{item.b.title}</dd></div><div><dt>שואל</dt><dd>{name}</dd></div><div><dt>בעלים</dt><dd>{item.c.owner}</dd></div><div><dt>תאריך</dt><dd>{new Date().toLocaleDateString("he-IL")}</dd></div></dl></div><div className="step-actions"><button className="secondary" onClick={()=>setStep(2)}>חזרה</button><button className="solid" onClick={()=>save(item.b.id,item.c.id,name.trim())}><Check/>אישור ההשאלה</button></div></>}</Modal>}
function BookDetail({book,members,close,change,remove}:{book:Book;members:string[];close:()=>void;change:(b:Book)=>void;remove:()=>void}){const[who,setWho]=useState(members[0]),[stars,setStars]=useState(5),[text,setText]=useState("");return <Modal close={close} wide><div className="detail"><Cover b={book}/><div><span className="eyebrow">{book.genre}</span><h2>{book.title}</h2><p>{book.author}</p><h3>עותקים</h3>{book.copies.map(c=><div className="copy-row" key={c.id}><b>{c.owner}</b><span>{c.location}</span><em>{c.status==="loaned"?`אצל ${c.borrower}`:"פנוי"}</em></div>)}<h3>דירוגים משפחתיים</h3>{book.ratings.map(r=><div className="review" key={r.member}><b>{r.member}</b><span>{"★".repeat(r.stars)}</span><p>{r.text}</p></div>)}<div className="review-form"><select value={who} onChange={e=>setWho(e.target.value)}>{members.map(x=><option key={x}>{x}</option>)}</select><select value={stars} onChange={e=>setStars(+e.target.value)}>{[5,4,3,2,1].map(x=><option key={x} value={x}>{x} כוכבים</option>)}</select><input value={text} onChange={e=>setText(e.target.value)} placeholder="ביקורת קצרה (לא חובה)"/><button onClick={()=>{const b={...book,ratings:[...book.ratings.filter(r=>r.member!==who),{member:who,stars,text}]};change(b);setText("")}}>שמירת דירוג</button></div><button className="reading-toggle" onClick={()=>change({...book,readers:book.readers.includes(who)?book.readers.filter(x=>x!==who):[...book.readers,who]})}>{book.readers.includes(who)?"סימון שסיים לקרוא":"סימון כקורא עכשיו"}</button><button className="danger" onClick={remove}><Trash2/>מחיקת הספר</button></div></div></Modal>}
function Wishlist({state,close,update}:{state:AppState;close:()=>void;update:(f:(s:AppState)=>AppState)=>void}){const[title,setTitle]=useState(""),[who,setWho]=useState(state.members[0].name);return <Modal close={close}><h2>רוצים לקנות</h2><div className="form inline"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="שם הספר"/><select value={who} onChange={e=>setWho(e.target.value)}>{state.members.map(x=><option key={x.name}>{x.name}</option>)}</select><button className="solid" disabled={!title} onClick={()=>{update(s=>({...s,wishlist:[...s.wishlist,{id:uid(),title,requestedBy:who}]}));setTitle("")}}><Plus/></button></div><div className="wish-list">{state.wishlist.map(w=><div key={w.id}><span><b>{w.title}</b><small>{w.requestedBy} ביקש/ה</small></span><button onClick={()=>update(s=>({...s,wishlist:s.wishlist.filter(x=>x.id!==w.id)}))}><Trash2/></button></div>)}</div></Modal>}
function Reading({state,close,update}:{state:AppState;close:()=>void;update:(f:(s:AppState)=>AppState)=>void}){const[book,setBook]=useState(state.books[0]?.id||""),[who,setWho]=useState(state.members[0].name);return <Modal close={close}><h2>קוראים עכשיו</h2><div className="form"><label>ספר<select value={book} onChange={e=>setBook(e.target.value)}>{state.books.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label><label>מי קורא?<select value={who} onChange={e=>setWho(e.target.value)}>{state.members.map(x=><option key={x.name}>{x.name}</option>)}</select></label><button className="solid full" onClick={()=>{update(s=>({...s,books:s.books.map(b=>b.id===book?{...b,readers:[...new Set([...b.readers,who])]}:b)}));close()}}>סימון כקורא עכשיו</button></div></Modal>}
