import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";
export const familyMembers=sqliteTable("family_members",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),color:text("color").notNull().default("#244d3e"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const titles=sqliteTable("titles",{id:integer("id").primaryKey({autoIncrement:true}),title:text("title").notNull(),author:text("author").notNull(),genre:text("genre").notNull().default("לא מסווג"),language:text("language").notNull().default("he"),isbn:text("isbn"),coverKey:text("cover_key"),rating:real("rating").notNull().default(0),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const copies=sqliteTable("copies",{id:integer("id").primaryKey({autoIncrement:true}),titleId:integer("title_id").notNull().references(()=>titles.id),ownerName:text("owner_name").notNull(),location:text("location").notNull().default("הבית המשותף"),status:text("status").notNull().default("available"),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const loans=sqliteTable("loans",{id:integer("id").primaryKey({autoIncrement:true}),copyId:integer("copy_id").notNull().references(()=>copies.id),borrowerName:text("borrower_name").notNull(),loanedAt:text("loaned_at").notNull().default(sql`CURRENT_TIMESTAMP`),returnedAt:text("returned_at")});
export const reviews=sqliteTable("reviews",{id:integer("id").primaryKey({autoIncrement:true}),titleId:integer("title_id").notNull().references(()=>titles.id),memberName:text("member_name").notNull(),rating:integer("rating").notNull(),body:text("body").notNull().default(""),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const wishlist=sqliteTable("wishlist",{id:integer("id").primaryKey({autoIncrement:true}),title:text("title").notNull(),requestedBy:text("requested_by").notNull(),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
export const appState=sqliteTable("app_state",{id:integer("id").primaryKey(),payload:text("payload").notNull(),updatedAt:text("updated_at").notNull().default(sql`CURRENT_TIMESTAMP`)});
